project: *project
  target: auto
  threshold: 10%
  if_not_found: error
  if_ci_failed: error
patch: *patch
  only_pulls: true
  target: 50%
  threshold: 10%
  if_not_found: error
  if_ci_failed: error

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default: off
      linux:
        flags: linux
        <<: *projects
      darwin:
        flags: darwin
        <<: *projects
    patch:
      default: off
      linux:
        flags: linux
        <<: *projects
      darwin:
        flags: darwin
        <<: *projects
    changes: true

flags:
  linux:
    paths:
      - /
  darwin:
    paths:
      - /

ignore:
  - "cmd"
  - "vendor"
  - "pkg/internal/fastwalk"
  - "pkg/internal/gopathwalk"
  - "pkg/internal/guru"
  - "pkg/internal/pool"

comment:
  behavior: default
  require_changes: true
