run:
  concurrency: 12
  deadline: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - "pkg/internal/fastwalk"
    - "pkg/internal/gopathwalk"
    - "pkg/internal/guru"
    - "pkg/internal/pool"
  skip-files:
    - ".*\\.pb\\.go"
    - ".*(.|_)gen\\.go"
  modules-download-mode: readonly

linters-settings:
  dupl:
    #threshold: 400
  errcheck:
    check-type-assertions: true
    check-blank: true
    # exclude: .errcheckignore
  funlen:
    lines: 60
    statements: 40
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/zchee/nvim-go
  golint:
    min-confidence: 0.3
  govet:
    enable-all: true
    check-shadowing: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    settings:
      hugeParam:
        sizeThreshold: 80
      rangeExprCopy:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 128
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    algo: cha
    check-exported: true
  unused:
    check-exported: true

linters:
  enable:
    - deadcode
    - depguard
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
  disable:
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - lll
    - nakedret
    - scopelint
    - unused
  fast: false

issues:
  exclude-use-default: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
